name: 'Enov8 Release Sync Github Action'
description: 'Push real-time updates on environment status, deployments, and version info to Enov8 — improving visibility, governance, and auditability across your IT landscape.'
inputs:
  version:
    description: 'Version to be sent'
    required: true
  system:
    description: 'System name (e.g., GDW (DEV))'
    required: true
  environment:
    description: 'Environment name (e.g., DEV)'
    required: true
  app_id:
    description: 'Enov8 app-id'
    required: true
  app_key:
    description: 'Enov8 app-key'
    required: true
  enov8_url:
    description: 'Full API URL (from secret)'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
