    - name: Check secrets presence
      run: |
        [ -z "${{ secrets.ENOV8_APP_ID }}" ] && echo "::error::ENOV8_APP_ID missing" || echo "ENOV8_APP_ID present"
        [ -z "${{ secrets.ENOV8_APP_KEY }}" ] && echo "::error::ENOV8_APP_KEY missing" || echo "ENOV8_APP_KEY present"
        [ -z "${{ secrets.ENOV8_BASE_URL }}" ] && echo "::error::ENOV8_BASE_URL missing" || echo "ENOV8_BASE_URL present"
